### ISSUE TITLE
AWSXRayRecorder.InitializeInstance(configuration)  taking  almost two minutes in local project initialization.

### ISSUE THREAD

**Issue by luchomejia** [aws/aws-xray-sdk-dotnet#135] opened 2020-06-02 17:14 UTC
Is it normal for the InitializeInstance method to take 2 minutes when starting the app?

I am using a Aspnet Core 3.1 app. I am working on capturing telemetry for my requests using XRay, so I am testing this locally. when running my app I have my Startup class constructor like this

 ```csharp 

public Startup(IConfiguration configuration)
 {
            _configuration = configuration;
            AWSXRayRecorder.InitializeInstance(_configuration);
}
```

That piece of code is taking almost two minutes before the application completely starts, which seems crazy to me compared to services like azure app insights telemetry.

I am also running the local XRay daemon and Im getting telemetry up by using the middleware as follows

```csharp
app.UseXRay("AppName")
```

**Comment by lupengamzn** [comment] 2020-06-02 19:34
Hi @luchomejia 

Thank you for bringing up this issue. Do you have a repro code of your application that we can test on our end?

**Comment by luchomejia** [comment] 2020-06-02 19:47
Hi @lupengamzn,   thanks for the quick response.

Unfortunately, this is a private repo so I will create a simple test project and try to repro so I can share it with you.

Since I come from an azure background I'm new to most of the aws services, so meanwhile, I would like to know if that `AWSXRayRecorder.InitializeInstance` is normally a method that takes a long time to run or if it is just something I'm experiencing myself.

I Will try to get you the test project later today.

**Comment by luchomejia** [comment] 2020-06-02 21:39
@lupengamzn @srprash I was able to reproduce it with a test project.  you can look at it here  https://github.com/luchomejia/testxraynetcore

Context:
I created the test project initially with only one nugget package

`<PackageReference Include="AWSXRayRecorder" Version="2.8.0" />`

With that in place the `InitializeInstance` method was taking around 20 seconds in my startup constructor, before it actually started got to the ConfigureServices method.

Even though 20 secons still seems too slow, it wasnt the same as my real project.
So I went ahead and added other nuget packages that I am currently using in my real project and ended up with this.
```
  <ItemGroup>
	  <PackageReference Include="AWS.Logger.SeriLog" Version="1.5.2" />
	  <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.101" />
	  <PackageReference Include="AWSSDK.S3" Version="3.3.110.61" />
	  <PackageReference Include="AWSXRayRecorder" Version="2.8.0" />
	  <PackageReference Include="AWSXRayRecorder.Handlers.System.Net" Version="2.7.0" />
  </ItemGroup>
```

Just after adding those, the load time went up from 20 secons to 1minute and 20 secons. so it added about 60 secons more(this is in debug mode).

**Comment by lupengamzn** [comment] 2020-06-08 21:57
Hey @luchomejia ,

Sorry for the late reply

The `AWSXRayRecorder.InitializeInstance(configuration)` API will initialize an `AWSXRayRecorder` instance with configurations extracted from `appsettings.json` file from your application. Please see [Link](https://github.com/aws/aws-xray-sdk-dotnet/blob/b1ade6460bb01fd55e5ae1be65dc408ff2ce6c56/sdk/src/Core/AWSXRayRecorder.netcore.cs#L66). That being said, the overhead introduced in this API may largely involve with dealing with parsing items from json file.

We have reproduced the repro app you provided and it turned out that it only required less than 1 second to run this method in debug mode. Do you happen to have any other large configuration items in the `appsettings.json` file that may slow down the configuration process?

Many thanks

**Comment by luchomejia** [comment] 2020-06-12 16:10
Thanks @lupengamzn 
That's weird, a big difference from what I'm experiencing. I'll try to run it this weekend in a different environment/laptop/network to see if any of that is affecting.

By the way, do you guys have some insights why why it may not work in Elastic Beanstalk, I get the recorders to work and send data from my local to aws using the local daemon, but when I deploy to EB im not getting anything.  The only thing I did on EB is to set up environment variables for the IAM user credentials, which are working fine for other services like cloudwatch logging. and enable the checkbox for XRay in the console configuration for EB.  Not sure if there is something additional I need to do to get it working. I would appreciate your input on that.

![Capture](https://user-images.githubusercontent.com/64533344/84523062-4d99f600-ac9d-11ea-9e8d-87f8c697ce47.JPG)

**Comment by lupengamzn** [comment] 2020-06-12 19:41
Hey @luchomejia 

AWS X-Ray .NET SDK is supportive for Elastic Beanstalk. When you deployed your application to EB, have you include the permission for Daemon to send traces to X-Ray in your IAM application role? The policy should include the X-Ray write permission. [Link](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts-roles-instance.html)

**Comment by luchomejia** [comment] 2020-06-14 22:02
Hey @lupengamzn 

Tested in a different network, got same results. 1 minute and 20 secons. So i tried to check fiddler looking for possible http requests upon instance initialization and found out a bunch of "Conection Failed" responses because of the requests timing out. Apparently a network issue trying to hit 169.254.169.254.  So I guess that is the reason it is taking that long.

![ConectionFailed](https://user-images.githubusercontent.com/64533344/84605085-31928200-ae60-11ea-83e3-da122fda932f.PNG)

By the way, was able to get this working in EB, you were right about me missing permission in the app role. I had added it to the IAM user I had configured in the environment variables and not to the instance role. The documentation is a little bit of a pain and really spread out in different articles to be honest. Thanks for the help on this one.

**Comment by srprash** [comment] 2020-06-15 01:19
Hi @luchomejia 
Are you running your application on an EC2 instance? The HTTP "Connection Failed" errors you are seeing correspond to the X-Ray SDK trying to fetch EC2 metadata from an instance local endpoint. Can you make sure you are not including the EC2 plugin in your configuration if you are not using an EC2 instance?

**Comment by luchomejia** [comment] 2020-06-15 01:27
Thanks for pointing this out @srprash .

That was indeed my issue. I had both EB and EC2 plugins but I was running in local and that was the reason it was taking so long.  When running in ElasticBeanstalk it is all working fine now after applying the right permissions as per @lupengamzn  answer. 

So even though the EB runs in an EC2 instance behind the scenes, I dont need the EC2 plugin when running in EB but only the "ElasticBeanstalkPlugin"?

**Comment by srprash** [comment] 2020-06-15 15:08
You can chain the two plugins together and get the metadata for both EBS and EC2 instances. 
As you said, the reason is that you're running in local and the EC2 plugin takes a while to fail, thus causing the slow down. I think it would be a good idea to add a shorter timeout to the plugin.

**Comment by luchomejia** [comment] 2020-06-17 01:51
Yep, I think a shorter timeout, plus some console logs would be really helpful.

Thanks both for the help.

**Comment by srprash** [comment] 2020-06-18 20:54
Absolutely. Will add a timeout to the metadata requests. You should see [these](https://github.com/aws/aws-xray-sdk-dotnet/blob/63bb73c4b3a1d0de4629d557e01d0dda9458668a/sdk/src/Core/Plugins/EC2Plugin.cs#L76) statements as debug logs for your application in case of EC2 metadata fetching failure.
Closing this issue now. Happy to help. :)

**Closed by srprash** 2020-06-18 20:54 UTC
