### ISSUE TITLE
Update AWSSDK.Core version

### ISSUE THREAD

**Issue by cfbao** [aws/aws-xray-sdk-dotnet#147] opened 2020-08-26 18:03 UTC
I understand that the goal for 3.x is to remove this dependency entirely, but for now, this dependency is lagging behind other AWS SDKs, and causes warnings in projects that use latest AWS SDKs (which requires a higher version of AWSSDK.Core).

Can a new 2.x release be made to update AWSSDK.Core?

**Comment by awssandra** [comment] 2020-08-26 21:46
Hi cfbao,

Completely reasonable ask. Let me get back to you shortly.

Thanks!
Sandra

**Comment by ckuehl** [comment] 2020-10-01 16:36
Any updates on this? Ideally, we'd like to avoid the build warnings that this is currently generating on all of our projects.

**Comment by lupengamzn** [comment] 2020-10-02 19:24
Hi @cfbao @ckuehl, we're currently working on this and will do a new release soon, thanks for the patience

**Comment by cfbao** [comment] 2020-10-27 21:01
I see that the master branch has fixed this issue 🎉
Will a release be out soon?

**Comment by lupengamzn** [comment] 2020-11-06 18:53
Hey @cfbao ,

This warning issue is caused by `AWSSDK.XRay` and we're removing it from `AWSXRayRecorder.Core`. #159  

We're also working on removing `AWSSDK.Core`, once these two PRs have been merged, a new release will be out soon.

Thanks for the patience

**Comment by johniwasz** [comment] 2020-11-09 23:07
Add one more developer to the list of folks being hit by these compatibility issues.

**Comment by mleybsage** [comment] 2020-11-27 14:14
And another developer waiting for this to be addressed

**Comment by ckuehl** [comment] 2020-12-18 16:16
@lupengamzn Is there anything else outstanding before cutting a release that fixes this?

**Comment by udlose** [comment] 2021-02-11 22:21
@lupengamzn  any updates here? TIA

**Comment by lupengamzn** [comment] 2021-03-03 22:31
Hey guys,

X-Ray .NET SDK `v2.10.0` has been released, which resolved the compatibility issue (**NU1608**) caused by `AWSSDK.Xray` while using the latest AWS SDK.

https://www.nuget.org/packages?q=awsxrayrecorder

**Closed** 2021-03-08 23:37 UTC
